name: Build Go Windows DLL

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build from"
        required: true
        default: "main"

jobs:
  build-windows-dll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Go 1.20
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Build DLLs for Windows (32-bit and 64-bit)
        run: |
          mkdir -p windows
          
          echo "Building 64-bit DLL..."
          GOOS=windows GOARCH=amd64 CGO_ENABLED=1 \
            go build -buildmode=c-shared -trimpath -ldflags="-s -w" \
            -o ./windows/openimsdk_amd64.dll ./

          echo "Building 32-bit DLL..."
          GOOS=windows GOARCH=386 CGO_ENABLED=1 \
            go build -buildmode=c-shared -trimpath -ldflags="-s -w" \
            -o ./windows/openimsdk_386.dll ./

      - name: Upload DLLs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-dlls
          path: ./windows/*.dll
